# ai



## WTF if this?

This is a multi-project-repo which contains conversations between me and
and various ais, and code generated by any or all of us as a result of
such conversations.  It is a pain in the butt to create repos from the
command line, so it's all in subdirs here.  Have fun.

