#!/usr/bin/perl
local(*ARGV)=\@_;

$\="\n";
while(<DATA>){
  @_=split;
  print shift;
  while(@_){
    print ". $_";
  };
}
__DATA__
BOOK/HTTP-Proxy-0.304.tar.gz HTTP::Proxy::BodyFilter::htmlparser
BPS/HTML-Quoted-0.05.tar.gz HTML::Quoted::Parser
CJK/HTML-PullParser-Nested-0.04.tar.gz HTML::PullParser::Nested
DJERIUS/HTML-TableParser-0.43.tar.gz HTML::TableParser HTML::TableParser::Table
DMAKI/HTML-HeadParser-Liberal-0.03.tar.gz HTML::HeadParser::Liberal
DMAKI/HTML-Parser-Stacked-0.00001.tar.gz HTML::Parser::Stacked
DRTECH/HTML-StripScripts-Parser-1.03.tar.gz HTML::StripScripts::Parser
EXODIST/DSL-HTML-0.006.tar.gz DSL::HTML::Parser
FVULTO/HTML-Toc-1.12.tar.gz HTML::_TokenTipParser HTML::_TokenTocBeginParser HTML::_TokenTocEndParser HTML::_TokenTocParser HTML::_TokenUpdateParser
GLEACH/Pod-HtmlEasy-v1.1.11a.tar.gz Pod::HtmlEasy::Parser
HERNAN/HTML-Robot-Scrapper-0.10.tar.gz HTML::Robot::Scrapper::Parser::Base
HERNAN/HTML-Robot-Scrapper-0.11.tar.gz HTML::Robot::Scrapper::Parser::Default HTML::Robot::Scrapper::Parser::HTML::TreeBuilder::XPath HTML::Robot::Scrapper::Parser::XML::XPath
JJNAPIORK/HTML-Zoom-0.009009.tar.gz HTML::Zoom::Parser::BuiltIn HTML::Zoom::SelectorParser
JKUTEJ/URL-Transform-0.01.tar.gz URL::Transform::using::HTML::Parser
JSWARTZ/HTML-Mason-1.05.tar.gz HTML::Mason::Parser
JTAVERNI/HTML-Content-Extractor-0.01.tar.gz HTML::Content::TokeParserTokenizer
JWIED/HTML-EP-0.2011.tar.gz HTML::EP::Parser
JWIED/Mail-IspMailGate-1.1013.tar.gz Mail::IspMailGate::Filter::Banner::HTML_Parser
KAWASAKI/HTML-TagParser-0.20.tar.gz HTML::TagParser HTML::TagParser::Element HTML::TagParser::Util
KENTARO/HTML-ValidationRules-0.02.tar.gz HTML::ValidationRules::Parser
KIMOTO/SPVM-Eg-0.015.tar.gz SPVM::Eg::HTMLDOMParser
LABZERONE/tmojo/HTML-Tmojo-0.300.tar.gz HTML::Tmojo::HttpArgParser
LNATION/HTML-TableContent-1.00.tar.gz HTML::TableContent::Parser
MATTP/HTML-Zoom-Parser-HTML-Parser-1.130810.tar.gz HTML::Zoom::Parser::HTML::Parser
MAUKE/HTML-Blitz-0.0901.tar.gz HTML::Blitz::Parser
MDOOTSON/Wx-0.9932.tar.gz Wx::HtmlParser Wx::HtmlWinParser
MIKI/HTML-Feature-3.00011.tar.gz HTML::Feature::FrontParser
NANZOU/HTML-WidgetValidator-0.0.3.tar.gz HTML::WidgetValidator::HTMLParser
OALDERS/HTML-Parser-3.83.tar.gz HTML::HeadParser HTML::Parser HTML::PullParser HTML::TokeParser
OVID/HTML-TokeParser-Simple-3.16.tar.gz HTML::TokeParser::Simple HTML::TokeParser::Simple::Token HTML::TokeParser::Simple::Token::Comment HTML::TokeParser::Simple::Token::Declaration HTML::TokeParser::Simple::Token::ProcessInstruction HTML::TokeParser::Simple::Token::Tag HTML::TokeParser::Simple::Token::Tag::End HTML::TokeParser::Simple::Token::Tag::Start HTML::TokeParser::Simple::Token::Text
PETDANCE/HTML-Lint-2.32.tar.gz HTML::Lint::Parser
RSAVAGE/HTML-Parser-Simple-2.02.tgz HTML::Parser::Simple HTML::Parser::Simple::Attributes HTML::Parser::Simple::Reporter
SDRABBLE/HTML-FormParser-0.11.tar.gz HTML::FormParser
SHMORIMO/HTML-Template-Parser-0.1011.tar.gz HTML::Template::Parser HTML::Template::Parser::ExprParser HTML::Template::Parser::Node HTML::Template::Parser::Node::ElsIf HTML::Template::Parser::Node::Else HTML::Template::Parser::Node::Group HTML::Template::Parser::Node::GroupEnd HTML::Template::Parser::Node::If HTML::Template::Parser::Node::IfEnd HTML::Template::Parser::Node::Include HTML::Template::Parser::Node::Loop HTML::Template::Parser::Node::LoopEnd HTML::Template::Parser::Node::Root HTML::Template::Parser::Node::String HTML::Template::Parser::Node::Unless HTML::Template::Parser::Node::UnlessEnd HTML::Template::Parser::Node::Var HTML::Template::Parser::NodeBuilder HTML::Template::Parser::TreeWriter HTML::Template::Parser::TreeWriter::HTP HTML::Template::Parser::TreeWriter::HTP::Expr HTML::Template::Parser::TreeWriter::TextXslate::Metakolon HTML::Template::Parser::TreeWriter::TextXslate::Metakolon::Expr
STEVIED/Dancer2-Plugin-MarkdownFilesToHTML-0.007.tar.gz Dancer2::Plugin::MarkdownFilesToHTML::MarkdownParser
TAKERU/HTML-TableParser-Grid-v0.0.5.tar.gz HTML::TableParser::Grid
TINITA/HTML-Template-Compiled-1.003.tar.gz HTML::Template::Compiled::Parser
TOBYINK/HTML-Data-Parser-0.006.tar.gz HTML::Data::Parser
TOBYINK/HTML-HTML5-Microdata-Parser-0.100.tar.gz HTML::HTML5::Microdata::Parser
TOBYINK/HTML-HTML5-Parser-0.992.tar.gz HTML::HTML5::Parser HTML::HTML5::Parser::Charset::DecodeHandle HTML::HTML5::Parser::Charset::Info HTML::HTML5::Parser::Charset::UnicodeChecker HTML::HTML5::Parser::Charset::UniversalCharDet HTML::HTML5::Parser::Charset::WebLatin1 HTML::HTML5::Parser::Charset::WebThai HTML::HTML5::Parser::Error HTML::HTML5::Parser::TagSoupParser HTML::HTML5::Parser::Tokenizer HTML::HTML5::Parser::UA
TOBYINK/HTML-Microformats-0.105.tar.gz HTML::Microformats::Datatype::DateTime::Parser HTML::Microformats::Mixin::Parser
TOBYINK/HTML-Zoom-Parser-HH5P-0.002.tar.gz HTML::Zoom::Parser::HH5P
WYANT/HTML-TableContentParser-0.305.tar.gz HTML::TableContentParser
